### ISSUE TITLE
Disable Ubuntu cloud init

### ISSUE THREAD

**Issue by luisnaranjo733** [diglos/ethereumonarm#11]
The Ubuntu server image ships with the cloud init feature turned on by default. This is completely redundant for this image, because the customization is baked into the ethereumonarm image, and does not at all rely on the Ubuntu cloud-init machinery to customize networking, storage, ssh, etc...

Probably best to just turn it off in rc.local and save a little bit of memory

> sudo echo "network: {config: disabled}" > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

https://askubuntu.com/a/1031626
https://askubuntu.com/questions/1060062/im-using-ubuntu-server-for-a-simple-home-server-do-i-need-cloud-init

**Comment by washosk** [comment]
Hi @luisnaranjo733  I just tested it, and  probably this change will be include in the next image version, I will do some mores testing but it is a very good idea. Thanks!
