### ISSUE TITLE
Websocket Error

### ISSUE THREAD

**Issue by raahimSal** [diglos/ethereumonarm#15]
When I try to connect to the geth websocket I am getting the following error:

2021/07/21 13:55:07 websocket: bad handshake (HTTP status 200 OK)

**Comment by diglos** [comment]
Hi, 

Can you write here how do you try to connect to Geth?, are you using the systemd service to start it?

**Comment by raahimSal** [comment]
yeah so the ws works when I use geth attach <ws address> on my pi. When I try to use my laptop to connect to the same WS it gives me the aforementioned error. The HTTP rpc works and I can connect to it on my laptop but just not the websocket rpc. I have tried both exposing the rpc to local network and open public and both give me the same error.

**Comment by diglos** [comment]
Hi,

If you are accessing from a different machine try adding `--ws.addr 0.0.0.0` to /etc/ethereum/geth.conf and restarting geth
