### ISSUE TITLE
ethonarm_21.03.00 won't finish setup

### ISSUE THREAD

**Issue by eccentricexit** [diglos/ethereumonarm#18]
I flashed my sd card with this image a few times today and the setup never finished.

Final result is an empty home folder and no `geth.service` running.

It seems `cloud-final.service` fails to `start Execute cloud user/final scripts.` (see image).

Output of `sudo systemctl`
![ethonarm](https://user-images.githubusercontent.com/9872474/137210594-2abe2893-7dd0-4386-97cf-9f93b9b75a6c.jpeg)

Image: ethonarm_21.03.00.img.zip
The hash matches `725359703b7c321f56a0e193be61c1f0102a23463549285e8f286e9fb6cc522f`

Hardware
```
    Raspberry 4 (model B 8GB);
    MicroSD Card (128 GB);
    4 TB SSD USB 3.0 disk or an SSD with an USB to SATA case;
    Connected to internet via cable .
```

**Comment by diglos** [comment]
Hi, never saw this before, we will take a look, sure. Thanks for reporting!!!

**Comment by eccentricexit** [comment]
I decided to give it a go again and I have more information.
I noticed the following:
The date is synced to some time in 2020
![Screenshot from 2021-10-14 10-19-11](https://user-images.githubusercontent.com/9872474/137325445-e54956ee-49a7-4bc1-b333-c360a5723af5.png)

`systemctl` thinks its been running since the 70s
![Screenshot from 2021-10-14 10-19-39](https://user-images.githubusercontent.com/9872474/137325469-a8f2bfc5-7195-433e-9e52-232261e60baa.png)

I went ahead and manually set the date using `timedatectl set-time` but it was moved back again after rebooting.

**Comment by diglos** [comment]
Hi,

Could you please run this command and paste here the output?:

`timedatectl status`

**Comment by diglos** [comment]
Yeah, seems you ran into a problem with the NTP server. I'm closing the issue as it is not related with the image. Feel free to reopen if you think otherwise.
