### ISSUE TITLE
Unsupported board type

### ISSUE THREAD

**Issue by Jeiwan** [diglos/ethereumonarm#26]
I bought a new Raspberry PI 4 with 8Gb, and, apparently, it's not supported by the ethereumonarm image. The device won't boot: the green led keeps signaling 4 long and 4 short blinks, which means "Unsupported board type" ([source](https://www.raspberrypi.com/documentation/computers/configuration.html#led-warning-flash-codes)).

My `/proc/cpuinfo`:
```
Hardware	: BCM2711
Revision	: d03115
Serial		: 100000008bd5d2bb
Model		: Raspberry Pi 4 Model B Rev 1.5
```

**Comment by Jeiwan** [comment]
It works on a newer version of Ubuntu: `ubuntu-20.04.4-preinstalled-server-arm64+raspi.img`

**Comment by gwenvador** [comment]
#28 I have the same issue but the upgraded version did not work.

**Comment by gwenvador** [comment]
I downloaded from https://www.ethereumonarm.com/downloads/ethonarm_21.03.00.img.zip
Is this build updated?

**Comment by gwenvador** [comment]
It worked with building its own image. so please update the download links in the docs with a newer image.
