### ISSUE TITLE
Not compatible with new raspberry pi 4B - 8GB 

### ISSUE THREAD

**Issue by gwenvador** [diglos/ethereumonarm#28]
I just purchased a new raspberry pi 4B and trying to boot with ethonarm_21.03.00.img.zip fails. 

> start.4elf: is not compatible
> This board requires newer software
> Get the latest software from https://www.raspberrypi.org/downloads/

Looking at other forum it seems that newest raspberry need updated OS. See https://raspberrypi.stackexchange.com/questions/127325/raspberry-pi-not-booting-recover4-elf-is-not-compatible

**Comment by gwenvador** [comment]
I build my own image with the updated ubuntu version and it worked. Need to update the docs with a new version

**Comment by diglos** [comment]
Done, will announce it tomorrow.

Thanks for noticing.
