### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cryptogohan** [diglos/ethereumonarm#3]
Just came to say thanks!

This older tutorial [over here](https://ethereum.org/en/developers/tutorials/run-node-raspberry-pi/) using what seems like diglos/pi-gen didn't work for me. The image somehow wouldn't complete set-up. Then I found the ethonarm twitter, the docs, and this repo. Works great! Looooooving the grafana dashboard too.

So thanks 🙏 ! She's purring like a happy kitty 😄 . If I see you in the next gitcoin round you'll have my support!!

**Comment by diglos** [comment]
Hey, thanks for taking the time to stop by and show support, we really appreciate it!
