### ISSUE TITLE
FAT Volume Not Supported

### ISSUE THREAD

**Issue by tbrent** [diglos/ethereumonarm#32]
This is on the latest image `ethonarm_22.04.00.img`. I've tried re-flashing multiple cards and I get the same error. I see `0x0b` for the format type on the error screen, is that expected?

![IMG_20220502_165639](https://user-images.githubusercontent.com/13439795/166332416-7f370656-df21-4ca3-84aa-696b4fce24dc.jpg)

**Comment by diglos** [comment]
Hi,

this seems a problem either with the Card or the card reader (or even with the Pi but this would be very odd). I would try flash it with a different utility:

https://www.balena.io/etcher/

Take a look at this as well:

https://forums.raspberrypi.com/viewtopic.php?t=294176

**Comment by tbrent** [comment]
It's working now -- looks like flashing it with Etcher produced a different result than the command line. Maybe this had to do with using `conv=sync` instead of `conv=fdatasync`? I was flashing on a mac and didn't have `fdatasync` available. 

Thanks for your help! Closing this one out
