### ISSUE TITLE
Nethermind version 1.14.0 crashes on PI4-8gb

### ISSUE THREAD

**Issue by handelaar2** [diglos/ethereumonarm#43]
Dit a fresh install on my Raspberry PI 4 (8gb). Only thing running is Nethermind (sudo systemctl start nethermind-goerli)
It crashes right after start due to what seems OOM
![2022-09-03_08-41-34](https://user-images.githubusercontent.com/28559038/188259251-9d280748-a831-45e9-9a6f-27283405bc45.png)

Same issue at a different place in the log:
![2022-09-03_08-40-39](https://user-images.githubusercontent.com/28559038/188259281-97743fef-f731-4720-9a8f-fd9f74ee0800.png)

Flashed SD card from: ethonarm_22.04.00.img.zip

Never had problems with Nethermind in the past running on RPI4.
On the console: 
![2022-09-03_10-09-50](https://user-images.githubusercontent.com/28559038/188262125-b1fcd2fa-0221-4d65-bb88-abb256de9ef5.png)

**Comment by diglos** [comment]
Solved with newer versions.
