### ISSUE TITLE
Instructions on how to install MEV

### ISSUE THREAD

**Issue by gwenvador** [diglos/ethereumonarm#47]
Can you please give instructions on how to install MEV-boost on already installed raspberry. I can't find the package in the apt.ethraspbian.com repository.

**Comment by thomasWos** [comment]
https://twitter.com/EthereumOnARM/status/1573338221224038402?s=20&t=iK6SmAqnTuHTFsqSR3pcnQ
Not sure the package is published...

You can have a look to this:
https://github.com/remyroy/ethstaker/blob/main/prepare-for-the-merge.md#choosing-and-configuring-an-mev-solution

And this to select a MEV relay
https://github.com/remyroy/ethstaker/blob/main/MEV-relay-list.md
(Maybe good to use a non-censoring mev-boost relay https://www.mevwatch.info/)

**Comment by diglos** [comment]
Published last week:

https://ethereum-on-arm-documentation.readthedocs.io/en/latest/user-guide/mev-boost.html
