### ISSUE TITLE
Is NanoPC-T4 still supported?

### ISSUE THREAD

**Issue by philknows** [diglos/ethereumonarm#5]
I'm trying to boot the latest image (March 2021 v21.03.00) on the NanoPC-T4. Unsure why it's not booting automatically from the SD card after using Etcher to write the image. It used to prioritize SD boot before the eMMC. Now it just boots right into the eMMC.

**Comment by diglos** [comment]
Hi, are you sure it is not booting from the SD card?, can you run this command?:

`df -h`

Nano is still supported (you need to switch to the new repository) but with 4 GB of RAM it is not the best option for running an Ethereum node nowadays.

Thanks!
