### ISSUE TITLE
Is this meant to boot from SD card at all times?

### ISSUE THREAD

**Issue by binomialstew** [diglos/ethereumonarm#62]
I was going to ask this in the discord channel, but it seems like I don't have access.

I've set up my Orange Pi 5 Plus with an NVME, flashed the SD card and ran through the setup. I can `ssh` to the `ethereum` account, I've changed my password, and I can see all the ethereum packages available.

One thing I am not clear about—is this meant to be booted from the SD card? I _thought_ the NVME was going to be set up to be the boot volume, but when I boot with the SD card removed, it does not allow me to ssh with the `ethereum` user. Don't we take a performance hit by running off the SD card?

**Comment by diglos** [comment]
It is. Recovering the board from a nvme disk failure can be tricky while you only get a faster boot (all processes are loaded in RAM and the Ethereum clients write and red on the NVMe disk).

Besides, this allows us to upgrade the whole distro in less than 10 minutes very easy (doing an APT upgrade sometimes brokes everything), see:

https://ethereum-on-arm-documentation.readthedocs.io/en/latest/quick-guide/download-and-install.html#image-upgrade
