### ISSUE TITLE
is it a problem with the disk?

### ISSUE THREAD

**Issue by brwab** [diglos/ethereumonarm#7]
i ran in to following issue:

04 00 00
May  7 14:35:26 ethereumonarm-4c4e87048 kernel: [ 2530.608415] sd 0:0:0:0: [sda] tag#3 uas_eh_abort_handler 0 uas-tag 21 inflight: CMD OUT
May  7 14:35:26 ethereumonarm-4c4e87048 kernel: [ 2530.608423] sd 0:0:0:0: [sda] tag#3 CDB: Write(10) 2a 00 00 cc 94 00 00 04 00 00
May  7 14:35:26 ethereumonarm-4c4e87048 kernel: [ 2530.614806] sd 0:0:0:0: [sda] tag#8 uas_eh_abort_handler 0 uas-tag 27 inflight: CMD OUT
May  7 14:35:26 ethereumonarm-4c4e87048 kernel: [ 2530.614818] sd 0:0:0:0: [sda] tag#8 CDB: Write(10) 2a 00 00 d2 94 00 00 04 00 00
May  7 14:35:30 ethereumonarm-4c4e87048 kernel: [ 2535.174869] sd 0:0:0:0: [sda] tag#9 uas_eh_abort_handler 0 uas-tag 28 inflight: CMD IN
May  7 14:35:30 ethereumonarm-4c4e87048 kernel: [ 2535.174887] sd 0:0:0:0: [sda] tag#9 CDB: Read(10) 28 00 00 6e 13 a0 00 00 08 00
May  7 14:35:32 ethereumonarm-4c4e87048 kernel: [ 2537.126896] sd 0:0:0:0: [sda] tag#10 uas_eh_abort_handler 0 uas-tag 29 inflight: CMD IN
May  7 14:35:32 ethereumonarm-4c4e87048 kernel: [ 2537.126914] sd 0:0:0:0: [sda] tag#10 CDB: Read(10) 28 00 00 10 38 d0 00 00 08 00
May  7 14:35:32 ethereumonarm-4c4e87048 kernel: [ 2537.142905] scsi host0: uas_eh_device_reset_handler start
May  7 14:35:37 ethereumonarm-4c4e87048 kernel: [ 2542.331180] xhci_hcd 0000:01:00.0: Timeout while waiting for setup device command
May  7 14:35:43 ethereumonarm-4c4e87048 kernel: [ 2547.707224] xhci_hcd 0000:01:00.0: Timeout while waiting for setup device command
May  7 14:35:43 ethereumonarm-4c4e87048 kernel: [ 2547.915023] usb 2-1: device not accepting address 2, error -62

**Comment by diglos** [comment]
Hi,

It seems a problem with the UAS (USB Attached SCSI) driver. Check your case chipset (by running `lsusb`) and make sure it is compatible with the Kernel. Please check this section on our guide:

https://ethereum-on-arm-documentation.readthedocs.io/en/latest/user-guide/storage.html

Other possible reason (we've seen this on a Geekwork case) is the USB cable, so try to connect another cable and check if this solves the issue.

Of course, it may be a disk problem, but based on our experience the most probably explanation is the chipset/cable incompatibility.
